const express = require("express")
const dotenv = require("dotenv")
const cors = require("cors")
const mongoose = require("mongoose")
const router_staff_api = require("./routes/staff/staff.api")
const router_salary_api = require("./routes/salary/salary.api")
const app = express()
dotenv.config()
mongoose.connect(process.env.NODE_DB).then(() => {console.log("Database connected")}).catch(() => {console.log("Failed to connect database")})
app.listen(process.env.PORT, () => {
 console.log(`Server is running on port ${process.env.PORT}`)
})
app.use(express.json())
app.use(cors())
app.use("/api", router_staff_api)
app.use("/api/v1", router_salary_api)
